### ISSUE TITLE
Missing 684 telebus areas 1,2,3 and 4 and more

### ISSUE THREAD

**Issue by Tombhob7** [philam/melbournetransportmap#101] opened 2019-12-14 12:47 UTC
The 684 bus is missing, so are the telebus areas around Lilydale/ Mooroolbark (areas 1,2,3 and 4). The 676 is going the wrong way. On the map it looks like the 663 and the 680 stop at the 673 Lilydale lake community centre stop. They do go past Lilydale lake but only the 673 actually goes inside and stops. The 677 doesn’t have a telebus area it just has a small hail and ride system. You missed the 664 deviation on Glen Park Rd (maybe on purpose). At Croydon Station you didn’t list its routes. The Warburton and **Healesville Rail Trail (**not yet open) are also missing. Thanks

**Comment by philam** [comment] 2019-12-14 23:28
Duplicate of #21 #57 #91 #20

**Closed** 2020-01-01 00:12 UTC
Labels: map fix
